name: minimalist
description: The minimalest minimal list

publish_to: 'none'

version: 3.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Redux
  flutter_redux: ^0.6.0
  redux: ^4.0.0+3
  redux_logging: ^0.4.0
  redux_persist: ^0.8.4
  redux_persist_flutter: ^0.8.2

  # Utils
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^0.1.3
  device_info: ^0.4.2+7
  flutter_svg: ^0.18.1
  google_sign_in: ^4.5.5
  http: ^0.12.2
  provider: ^4.3.2+2
  timeago: ^2.0.27
  url_launcher: ^5.5.0

  # Firebase
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    -   family: CrustCons
        fonts:
          -   asset: assets/fonts/CrustCons.ttf

    -   family: PTSans
        fonts:
          -   asset: assets/fonts/PTSans-Regular.ttf
          -   asset: assets/fonts/PTSans-Bold.ttf


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
